stages:             # these stages (jobs) form the CICD pipeline
  - mavenbuild      # JOB to build Spring Boot app
  - maventest       # JOB to run Spring Boot tests
  - mavendeploy     # JOB to deploy Spring Boot app
  - androidbuild    # JOB to build Android app
  - androidtest     # JOB to run Android tests

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend/project/project2
    - mvn package
  artifacts:
    paths:
      - Backend/project/project2/target/*.jar
  only:
    refs:
      - main
    changes:
      - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend/project/project2
    - mvn test
  only:
    refs:
      - main
    changes:
      - Backend/**/*

auto-deploy:
  stage: mavendeploy
  tags:
    - springboot_tag
  script:
    - cd Backend/project/project2
    - mvn clean package
    - sudo mv target/onetoone-1.0.0.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - main
    changes:
      - Backend/**/*

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/CardsWithFriends/gradlew
  script:
    - cd Frontend/CardsWithFriends
    - ./gradlew build
  only:
    refs:
      - main
    changes:
      - Frontend/CardsWithFriends/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/CardsWithFriends/gradlew
  script:
    - cd Frontend/CardsWithFriends
    - ./gradlew test
  only:
    refs:
      - main
    changes:
      - Frontend/CardsWithFriends/**/*