stages:
  - mavenbuild
  - maventest
  - mavendeploy
  - androidbuild
  - androidtest

# -------------------------------
# MAVEN BUILD (Java 17)
# -------------------------------
maven-build:
  image: maven:3.9-eclipse-temurin-17
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend/project/project2
    - mvn package
  artifacts:
    paths:
      - Backend/project/project2/target/*.jar
  only:
    refs:
      - main
    changes:
      - Backend/**/*

# -------------------------------
# MAVEN TEST (Java 17)
# -------------------------------
maven-test:
  image: maven:3.9-eclipse-temurin-17
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend/project/project2
    - mvn test
  only:
    refs:
      - main
    changes:
      - Backend/**/*

# -------------------------------
# MAVEN DEPLOY (Java 17)
# -------------------------------
auto-deploy:
  image: maven:3.9-eclipse-temurin-17
  stage: mavendeploy
  tags:
    - springboot_tag
  script:
    - cd Backend/project/project2
    - mvn clean package
    - sudo mv target/onetoone-1.0.0.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - main
    changes:
      - Backend/**/*

# -------------------------------
# ANDROID BUILD
# -------------------------------
android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/CardsWithFriends/gradlew
  script:
    - cd Frontend/CardsWithFriends
    - ./gradlew build
  only:
    refs:
      - main
    changes:
      - Frontend/CardsWithFriends/**/*

# -------------------------------
# ANDROID TEST
# -------------------------------
android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/CardsWithFriends/gradlew
  script:
    - cd Frontend/CardsWithFriends
    - ./gradlew test
  only:
    refs:
      - main
    changes:
      - Frontend/CardsWithFriends/**/*
